CREATE DATABASE IF NOT EXISTS ebytr;

USE ebytr;

CREATE TABLE tasks
(
	id INT NOT NULL AUTO_INCREMENT,
	task VARCHAR(30) NOT NULL,
	status VARCHAR(15) NOT NULL,
	date VARCHAR(20) NOT NULL,
	PRIMARY KEY(id)
);